name: Build Images
on:
  - push
  - pull_request
jobs:
  find-cfs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Discover Containerfiles
        run: echo cf_matrix=$(ci/discover_cfs.sh) >> $GITHUB_ENV
      - name: Output discovered Containerfile matrix
        run: echo ${{ env.cf_matrix }}
      - name: Set matrix to disocovered Containerfiles
        id: set-matrix
        run: echo "::set-output name=matrix::${{ env.cf_matrix }}"

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: quay.io
      IMAGE_USER: rydrew
    strategy:
      matrix: ${{ fromJSON(needs.find-cfs.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Echo Matrix Permutation
        run: |
            echo "containerfile: ${{ matrix.contailerfile }}"
            echo "image name: ${{ matrix.image_name }}"
            echo "tag prefix: ${{ matrix.tag_prefix }}"
      - name: Build ${{ matrix.containerfile }}
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ matrix.tag_prefix }}${{ github.sha }}
          dockerfiles: ${{ matrix.containerfile }}
      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_USER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print image URL
        run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
