name: Build Images

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      diff_branch:
        description: 'Upstream branch for determining changes'
        default: 'master'
      run_all:
        description: 'Run all builds regardless of changes?'
        default: 'false'

jobs:
  create_matrix:
    runs-on: ubuntu-latest
    name: Create Build Matrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Echo manual trigger params
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Set upstream branch
        run: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
            then
                echo UPSTREAM_BRANCH=${{ github.event.inputs.diff_branch }} >> $GITHUB_ENV
            else
                echo UPSTREAM_BRANCH=master >> $GITHUB_ENV
            fi

      - name: Build job matrix (changed only)
        if: >-
            (
                github.event_name != 'workflow_run' ||
                (github.event_name == 'workflow_run' && toJSON(github.event.workflow_run.inputs.run_all) == false)
            )
        run: echo matrix=`python ci/build_matrix.py --changed-only --upstream ${{ env.UPSTREAM_BRANCH }}` >> $GITHUB_ENV
      - name: Build job matirx (all)
        if: (github.event_name == 'workflow_run' && toJSON(github.event.workflow_run.inputs.run_all) == true)
        run: echo matrix=`python ci/build_matrix.py --upstream ${{ env.UPSTREAM_BRANCH }}` >> $GITHUB_ENV

      - name: Set job matrix
        id: set-matrix
        run: echo '::set-output name=matrix::${{ env.matrix }}'

      - name: Echo matrix variable
        run: |
            cat << EOF
            ${{ steps.set-matrix.outputs.matrix }}
            EOF
      - name: Sanity check by parsing matrix using fromJSON
        run: echo ${{ fromJSON(steps.set-matrix.outputs.matrix) }}

  build_push:
    needs: create_matrix
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJSON(needs.create_matrix.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.benchmark }} (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v2
      - name: Echo Matrix Permutation
        run: |
            cat << EOF
            ${{ toJSON(matrix) }}
            EOF
      - name: Update apt cache
        run: sudo apt update
      - name: Install podman and qemu-user-static
        run: sudo apt install -y podman qemu-user-static
      - name: Build ${{ matrix.containerfile }}
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image_name }}
          tags: ${{ github.sha }}${{ matrix.tag_suffix }} latest${{ matrix.tag_suffix }}
          dockerfiles: ${{ matrix.dockerfile }}
      - name: Push ${{ matrix.dockerfile }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/${{ secrets.REGISTRY_USER }}
          username: ${{ secrets.REGISTRY_AUTH_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print image URL
        run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
