name: Documentation Build Test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get install -y pandoc
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install benchmark-wrapper
        run: pip install .
      - name: Install test dependencies
        run: pip install snafu[testsci]
      - name: Run Tox
        run: tox -e py36-docs,py37-docs,py38-docs
