name: Build Images
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      diff_branch:
        description: 'Upstream branch for determining changes'
        default: 'master'
      run_all:
        description: 'Run all tests regardless of changes?'
        default: 'false'
jobs:
  find-cfs:
    if: >-
        github.event_name != 'workflow_run' ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
        (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ok to test'))
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Echo manual trigger params
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Set upstream branch
        run: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
            then
                echo UPSTREAM_BRANCH=${{ github.event.inputs.diff_branch }} >> $GITHUB_ENV
            else
                echo UPSTREAM_BRANCH=master >> $GITHUB_ENV
            fi
      - name: Fetch upstream branch
        run: git fetch origin ${{ env.UPSTREAM_BRANCH }}
      - name: Echo git information
        run: |
            echo "Current branch: `git branch --show-current`"
            echo "Origin URL(s): `git remote get-url origin`"
            echo "Changes: `git diff origin/${{ env.UPSTREAM_BRANCH }} --name-only`"
      - name: Discover Containerfiles
        run: echo cf_matrix=$(ci/discover_cfs.sh ${{ env.UPSTREAM_BRANCH }}) >> $GITHUB_ENV
      - name: Filter container files with ignore key
        run: >-
            echo cf_matrix=`echo "$cf_matrix" | jq -c
            '{"include": .include | map(select(.ignore == "false"))}'` >> $GITHUB_ENV
      - name: Filter container files with no changes
        if: >-
            github.event_name != 'workflow_dispatch' ||
            (github.event_name == 'workflow_dispatch' && github.event.inputs.run_all == 'false')
        run: >-
            echo cf_matrix=`echo "$cf_matrix" | jq -c
            '{"include": .include | map(select(.changed == "true"))}'` >> $GITHUB_ENV
      - name: Set matrix to containerfiles that need to be tested
        id: set-matrix
        run: echo '::set-output name=matrix::${{ env.cf_matrix }}'
      - name: Echo matrix variable
        run: echo '${{ steps.set-matrix.outputs.matrix }}'
      - name: Parse matrix using fromJSON
        run: echo ${{ fromJSON(steps.set-matrix.outputs.matrix) }}

  build-save-test:
    needs: find-cfs
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJSON(needs.find-cfs.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.benchmark }} (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v2
      - name: Echo Matrix Permutation
        run: |
            cat << EOF
            ${{ toJSON(matrix) }}
            EOF
      - name: Update apt cache
        run: sudo apt update
      - name: Install podman and qemu-user-static
        run: sudo apt install -y podman qemu-user-static
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install benchmark-wrapper
        run: pip install .
      - name: Install test dependencies
        run: pip install snafu[testsci]
      - name: Set image tag
        run: |
            echo IMAGE_TAG=${{ matrix.tag_prefix }}${{ github.sha }} >> $GITHUB_ENV
      - name: Set artifact name
        run: |
            echo ARTIFACT_NAME=${{ matrix.image_name }}.${{ env.IMAGE_TAG }} >> $GITHUB_ENV
      - name: Build ${{ matrix.containerfile }}
        id: build-image
        run: >-
            podman build . -t ${{ matrix.image_name }}:${{ env.IMAGE_TAG }}
            -f ${{ matrix.containerfile }} --arch ${{ matrix.arch }}
      - name: Export image to archive
        run: >-
            podman save --output ${{ env.ARTIFACT_NAME }}.tar
            localhost/${{ matrix.image_name }}:${{ env.IMAGE_TAG }}
      - name: Save Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.tar
          retention-days: 10
      - name: Set benchmark image environment variable
        run: |
            echo ${{ matrix.env_var }}=localhost/${{ matrix.image_name }}:${{ env.IMAGE_TAG }} >> $GITHUB_ENV
      - name: Run functional tests
        run: tox -e functional -- -m ${{ matrix.benchmark }}
