name: Push Test Images
on:
  workflow_run:
    workflows: ["Build Images"]
    types: [completed]
jobs:
  push-cfs:
    if: github.event.workflow_run.conclusion != 'cancelled'
    runs-on: ubuntu-latest
    env:
        DOWNLOAD_PATH: artifacts
    steps:
      - name: Install podman
        run: sudo apt update && sudo apt install -y podman
      - name: Download all built images
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: functional.yml
          workflow_conclusion: neutral
          run_id: ${{ github.event.workflow_run.id }}
          path: ${{ env.DOWNLOAD_PATH }}
      - name: Display directory structure
        run: |
            ls -R ${{ env.DOWNLOAD_PATH }}
      - name: Login to quay.io
        run: >-
            podman login --password ${{ secrets.REGISTRY_PASSWORD }}
            --username ${{ secrets.REGISTRY_AUTH_USER }} quay.io
      - name: Load and push images
        run: |
            image_archives=(`find ${{ env.DOWNLOAD_PATH }} -name '*.tar'`)

            for image in ${image_archives[*]}
            do
                image_archive_name=`echo $image | awk -F "/" '{print $(NF-1)}'`
                image_name=`echo $image_archive_name | cut -d'.' -f1`
                image_tag=`echo $image_archive_name | cut -d'.' -f2`
                podman load -i $image
                podman image push quay.io/${{ secrets.REGISTRY_USER }}/$image_name:$image_tag
                echo "Pushed ${image_name}:${image_tag}!"
            done
