name: Unit Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [6, 7, 8, 9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.${{ matrix.pyver }}
      - name: Install tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3${{ matrix.pyver }}-unit
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-py3${{ matrix.pyver }}
          path: .coverage-py3${{ matrix.pyver }}
  coverage_report:
    needs: unit_tests
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v2
      - name: Unpack artifact
        run: find . -name ".coverage*" -exec mv {} . \;
      - name: Create coverage report
        run: tox -e coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
