name: Unit Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [6, 7, 8, 9]
    name: Run Unit Tests -- Python 3.${{ matrix.pyver }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.${{ matrix.pyver }}
      - name: Install tox and coverage
        run: pip install tox
      - name: Run Tox
        run: tox -e py3${{ matrix.pyver }}-unit
      - name: Generate coverage report
        run: coverage xml
      - name: Upload coverage report
        if: matrix.pyver == 6
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: unit,gha,python-3.${{ matrix.pyver }}
