name: Unit Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install benchmark-wrapper
        run: pip install .
      - name: Install test dependencies
        run: pip install snafu[testsci]
      - name: Run Tox
        run: tox -e py36-unit,py37-unit,py38-unit
      - name: Upload coverage reports
        uses: codecov/codecov-action@v1
        with:
          files: ./.coverage*
          flags: ${{ matrix.python-version }}
