name: Unit Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py36-unit,py37-unit,py38-unit,coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
